import './globals.css'
import 'swiper/css';
import 'swiper/css/pagination';

import '../public/Styles/Home.css'
import '@/public/font/dmsans/style.css'
import {Inter} from 'next/font/google'

import Home from "@/components/home/Home";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";

// const inter = Inter({subsets: ['latin']})

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({children}) {
   return (
       <html lang="en">
       <body>
       <div>
          {children}
       </div>
       </body>
       </html>
   )
}
